apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mode
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      release: canary
  template:
    metadata:
      name: deploy-pod
      namespace: defaults
      labels:
        app: myapp
        release: canary
    spec:
      containers:
      - name: nginx-deploy-pod-container
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80