# service account，顾名思义，主要是给service使用的一个账号。
# 具体一点，就是为了让Pod中的进程、服务能访问k8s集群而提出的一个概念，基于service account，pod中的进程、服务能获取到一个username和令牌Token，从而调用kubernetes集群的api server。
# service account中最主要的内容是一个secret资源，其中包含了认证所需的token、根CA等
# https://blog.csdn.net/weiyuanke/article/details/87373217

# 声明创建ServiceAccount 简称sa
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: admin

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    author: "Smmurfs的格格巫"
spec:
  containers:
  - name: nginx-test
    image: nginx
    ports:
    - name: http
      containerPort: 80
  serviceAccountName: admin # 设置pod使用自定义的sa(ServiceAccount)账号