apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-mp
  namespace: default
data: # 设置配置文件内容
  nginx.conf: | # 设置配置文件文件名，| 是格式要求

    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        server {
            listen 80;
            server_name localhost;
            location / {
                root /home/html;
                index index.html;
            }
        }

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginxapp
  labels:
    app: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: nginxweb
        image: nginx:1.15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx
            mountPath: /etc/nginx/nginx.conf # 设置挂在路径
            subPath: nginx.conf # 设置只挂在这个文件
          - name: html
            mountPath: /home/html
      volumes:
        - name: nginx # 设置存储卷
          configMap:
            name: nginx-mp
        - name: html
          hostPath:
            path: /root/html
            type: DirectoryOrCreate