apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  nfs:
    path: /disk-1/v1
    server: node-2
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  nfs:
    path: /disk-1/v2
    server: node-2
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
spec:
  nfs:
    path: /disk-1/v3
    server: node-2
  accessModes:
    - "ReadWriteMany"
  capacity:
    storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv04
spec:
  nfs:
    path: /disk-1/v4
    server: node-2
  accessModes:
    - "ReadWriteMany"
  capacity:
    storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv05
spec:
  nfs:
    path: /disk-1/v5
    server: node-2
  accessModes: ["ReadWriteMany", "ReadWriteOnce", "ReadOnlyMany"]  
  capacity:
    storage: 10Gi